// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EwSauQogEziJRe2pH-UEZPlbgFds_nE',
    appId: '1:385910156080:web:c7073884ec82e59a94b6f5',
    messagingSenderId: '385910156080',
    projectId: 'vitaltrack-dd273',
    authDomain: 'vitaltrack-dd273.firebaseapp.com',
    storageBucket: 'vitaltrack-dd273.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQ7GzRZY9yMSY3Av4gYXwmbnUCA2427I',
    appId: '1:385910156080:android:8e1389f5b672e43294b6f5',
    messagingSenderId: '385910156080',
    projectId: 'vitaltrack-dd273',
    storageBucket: 'vitaltrack-dd273.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaojMI1g_d067H1QnKl3Qw6ZuW1r1jOgk',
    appId: '1:385910156080:ios:46d10a4208ea8c6094b6f5',
    messagingSenderId: '385910156080',
    projectId: 'vitaltrack-dd273',
    storageBucket: 'vitaltrack-dd273.firebasestorage.app',
    iosBundleId: 'com.example.vitaltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaojMI1g_d067H1QnKl3Qw6ZuW1r1jOgk',
    appId: '1:385910156080:ios:46d10a4208ea8c6094b6f5',
    messagingSenderId: '385910156080',
    projectId: 'vitaltrack-dd273',
    storageBucket: 'vitaltrack-dd273.firebasestorage.app',
    iosBundleId: 'com.example.vitaltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5EwSauQogEziJRe2pH-UEZPlbgFds_nE',
    appId: '1:385910156080:web:2e7b5e1fc063985094b6f5',
    messagingSenderId: '385910156080',
    projectId: 'vitaltrack-dd273',
    authDomain: 'vitaltrack-dd273.firebaseapp.com',
    storageBucket: 'vitaltrack-dd273.firebasestorage.app',
  );

}